[package]
name = "yaak-sse"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
ts-rs = { version = "10.0.0", features = ["serde-json-impl"] }
